Add MAILCHIMP_API_KEY

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,6 +43,13 @@ jobs:
             echo "https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository"
             exit 1
           fi
+      - name: Check for MAILCHIMP_API_KEY
+        run: |
+          if [ -z "${{ secrets.MAILCHIMP_API_KEY }}" ]; then
+            echo "Error: MAILCHIMP_API_KEY is not set in GitHub secrets."
+            echo "Please set the MAILCHIMP_API_KEY secret in your repository settings."
+            exit 1
+          fi
       - name: Run tests
         run: pytest
         env:
